package ua.questplay.skillsplugin.skills;

public enum SkillType {
    THIEF_MONEY,
    THIEF_SPEED,
    THIEF_HASTE,
    THIEF_EXP,
    THIEF_CAUTION,
    THIEF_SPECIALIZATION,

    KILLER_MONEY,
    KILLER_SPEED,
    KILLER_MURDER,
    KILLER_HASTE,
    KILLER_VAMPIRISM,
    KILLER_RECOVERY,

    MERCHANT_MONEY,
    MERCHANT_LUCK,
    MERCHANT_EXP,
    MERCHANT_RUN,
    MERCHANT_HERO,
    MERCHANT_BLESSING,

    TANK_MONEY,
    TANK_BLOCK,
    TANK_PARRY,
    TANK_BALANCE,
    TANK_BLOCK_AURA,
    TANK_REDIRECT_AURA
}