name: SkillsPlugin
version: ${version}
bootstrapper: ua.questplay.skillsplugin.SkillsPluginBootstrap
main: ua.questplay.skillsplugin.SkillsPlugin
api-version: '1.21'
authors:
  - 'Quest_play'
description: "Adds game classes to your server."
website: ""

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true

    SimpleClans:
      load: BEFORE
      required: true


permissions:
  skillsplugin.*:
    description: "Full access to plugin commands."
    children:
      skillsplugin.class: true
      skillsplugin.skills: true
      skillsplugin.reload: true
      skillsplugin.give_skill: true
      skillsplugin.reset_command: true
  skillsplugin.class:
    description: "Access to class selection."
    default: true
  skillsplugin.skills:
    description: "Accessing the Skills Menu"
    default: true
  skillsplugin.reload:
    description: "Access to reload configuration"
    default: op
  skillsplugin.give_skill:
    description: "Access to Skill Issuance"
    default: op

  skillsplugin.reset_command:
    description: "Access to class reset"
    default: true
